services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres_db_for_LifeQualAbgabearbeit
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: LifeQual_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    external: true